### ISSUE TITLE
Should different names be allowed to match the same content?

### ISSUE THREAD

**Issue by vext01** [softdevteam/fm#10]
Here's an in interesting one.

```
assert!(helper("$1 $1 $1", "a a a"));
assert!(helper("$1 $2 $3", "a a a"));
```

Using the same name matchers as in the repo.

I expected the latter to fail because I wasn't expecting different names to be allowed to assume the same value.

Now a real world example. Here's what a TIR test looks like:
```
assert_tir(
    "live($a)\n\
    $a = call(add6, [1u64, 1u64, 1u64, 1u64, 1u64, 1u64])\n\
    dead($a)",
    &tir_trace,
);
```

`assert_tir()` just stringifies the TIR trace and tries to match the given pattern using the following name matchers:
```
let ptn_re = Regex::new(r"\$.+?\b").unwrap();
let text_re = Regex::new(r"\$?.+?\b").unwrap(); // Optional `$` prefix.
```

Then to test a failing match, I naively flipped `$a` on the first line of the pattern to `$c` and was surprised to see it matched. Of course, it's ok for both `$a` and `$c` to match the same content.

But should it be? Perhaps I want to know that the variable used in `live` is distinct from the one in the `call` and the `dead`.

**Comment by ltratt** [comment]
> I expected the latter to fail because I wasn't expecting different names to be allowed to assume the same value.

Good question. I think the default should be "they can be the same" but I'm happy to add an option to enforce distinctness. I think people mostly won't need that option (plus it will be a bit slow), hence making it non-default.

**Comment by vext01** [comment]
I can live with that.
