### ISSUE TITLE
Two consecutive wildcards crash FM.

### ISSUE THREAD

**Issue by ptersilie** [softdevteam/fm#34]
@vext01 and I triggered a bug in FM. If your pattern has two consecutive wildcards with a newline in between FM crashes:
```
thread 'tests::defaults' panicked at 'begin <= end (3 <= 0) when slicing `...`', src/lib.rs:357:28
```
See test:
```diff
diff --git a/src/lib.rs b/src/lib.rs
index c4fbca4..1c83515 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -523,6 +523,7 @@ mod tests {
             FMatcher::new(ptn).unwrap().matches(text).is_ok()
         }
         assert!(helper("", ""));
+        assert!(helper("...\n...", ""));
         assert!(helper("\n", ""));
         assert!(helper("", "\n"));
         assert!(helper("a", "a"));
```

I guess it doesn't make sense to do this in a pattern, but maybe a user friendly message would help here.

**Comment by ltratt** [comment]
Good spot!

**Comment by ltratt** [comment]
I have a fix for this but we need to either merge or close https://github.com/softdevteam/fm/pull/33 before I raise the fix, as it conflicts with that PR.

**Comment by ltratt** [comment]
Was fixed in https://github.com/softdevteam/fm/pull/35.
