### ISSUE TITLE
Incorrect error line?

### ISSUE THREAD

**Issue by vext01** [softdevteam/fm#5]
I added the test:
```
assert_eq!(helper("...\nline2\nline3\nline4\n", "line1\nline2\nline3\nbadgers\nline5"), 4);
```

Which gives fails, as the failure line reported is `3`, not as I expected `4`. I expected `4` because the first line in the text which doesn't match is `badgers` on line 4.

Did I misunderstand something, or is that a bug?

**Comment by vext01** [comment]
Replacing the `...` elision with `line1` reports line 4 as I'd expect.

**Comment by ltratt** [comment]
It's a bug. I'll look into it.
