### ISSUE TITLE
Potential bug in name matcher?

### ISSUE THREAD

**Issue by vext01** [softdevteam/fm#9]
I've added the following case to the name matcher test:

```
 assert!(helper("$1", "$2")); 
```

The regexs in the helper remain the same:
```
let nameptn_re = Regex::new(r"\$.+?\b").unwrap();
let name_re = Regex::new(r".+?\b").unwrap();
```

The FM matcher fails to match this.

I was expecting this to match, because the following assertions are true:
```
    assert!(Regex::new(r"\$.+?\b").unwrap().is_match("$1"));
    assert!(Regex::new(r".+?\b").unwrap().is_match("$2"));
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=516f4760b8692b180dba47073a23af32)

I'm not sure if my expectations are wrong, or if it's a bug.

**Comment by ltratt** [comment]
I *think* that this:

```
assert!(Regex::new(r".+?\b").unwrap().is_match("$2"));
```

might not be doing what you think. I think it's matching either the empty string (does `\b` match `$`?) or at best just `$`, leaving either `$2` or `2` unmatched and hence causing FM to signal failure.

**Comment by vext01** [comment]
Ah, `$` isn't matched by `\b`, so I think I need to adjust the matching regex to account for a potential `$` prefix.

**Comment by vext01** [comment]
The problem is, the point between `$` and `2` is a unicode word boundary.

The regex matches `$` and `2` separately, but not together. Verified by iterating over matches.
